### ISSUE TITLE
Issue with inverted 

### ISSUE THREAD

**Issue by diiiv9** [SwiftFiddle/swiftregex#206]
The following show a compile error in swift and the Builder DSL. 
The pattern : `\[\[([^\]\|]+)\|*([^\]\|]*)\]\]`
gives : 
`Regex {
  "[["
  Capture {
    OneOrMore(.anyOf("]|").inverted)
  }
  ZeroOrMore {
    "|"
  }
  Capture {
    ZeroOrMore(.anyOf("]|").inverted)
  }
  "]]"
}
.anchorsMatchLineEndings()`

**Comment by kishikawakatsumi** [comment]
Thanks for the report. However, converting to RegexBuilder just uses the [regex component](https://github.com/apple/swift-experimental-string-processing) provided by Apple. Converting this regex to RegexBuilder in the latest Xcode 15 beta gives the same result and compile error. Please report this issue to Apple, not to us.

https://github.com/SwiftFiddle/swiftregex/assets/40610/55d32b16-0b12-45e9-b89e-cc8666d9639d
