### ISSUE TITLE
member 'inverted' in 'CharacterClass' produces result of type 'RegexComponent', but context expects 'CharacterClass'

### ISSUE THREAD

**Issue by mirkokg** [SwiftFiddle/swiftregex#325]
Using following regex as an input: `[^/]*test[^/]*` produces:

```
Regex {
  ZeroOrMore(.anyOf("/").inverted)
  "test"
  ZeroOrMore(.anyOf("/").inverted)
}
.anchorsMatchLineEndings()
```

that regex builder code produces an error:

```
<stdin>:23:26: error: member 'inverted' in 'CharacterClass' produces result of type 'RegexComponent', but context expects 'CharacterClass' 21 | 22 | let regex_BD66AC71994F48BBA47E580B41A636AA = Regex { 23 | ZeroOrMore(.anyOf("/").inverted) | `- error: member 'inverted' in 'CharacterClass' produces result of type 'RegexComponent', but context expects 'CharacterClass' 24 | "test" 25 | ZeroOrMore(.anyOf("/").inverted)
```

it should be:

```
Regex {
  ZeroOrMore(CharacterClass.anyOf("/").inverted)
  "test"
  ZeroOrMore(CharacterClass.anyOf("/").inverted)
}
.anchorsMatchLineEndings()
```

**Comment by kishikawakatsumi** [comment]
Same as https://github.com/SwiftFiddle/swiftregex/issues/206

Thanks for the report. However, converting to RegexBuilder just uses the [regex component](https://github.com/apple/swift-experimental-string-processing) provided by Apple. Converting this regex to RegexBuilder in the latest Xcode 15.3 gives the same result and compile error. Please report this issue to Apple, not to us.

https://github.com/SwiftFiddle/swiftregex/assets/40610/d070a425-3e2f-4ce4-be55-c3492bc90352
